version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:jessie-browsers # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: set NODE_OPTIONS=--max_old_space_size=8192
      - run: npm install
      - run: npm run local
      - run: npm run report
      - Build_artifacts:
        path: /home/circleci/project/allure-report/